"use client"
// data.jsx
const eventData = [
    { sno: 1, date: '11.07.22', eventName: 'Awareness Propgrammes & Rallies on Usage of Plastic', domain: 'Environmental projects', participants: 82 },
    { sno: 2, date: '11.07.22', eventName: 'World Population Day', domain: 'Awareness Compaign', participants: 81 },
    { sno: 3, date: '16.07.22', eventName: 'Workshops on Cloth Bags Jute Bags Making', domain: 'Environmental projects', participants: 85 },
    { sno: 4, date: '19.07.22', eventName: 'Awareness Programmes on (Organic Waste Management, Sewage Handling Practices, Use of Organic Fertilizers, Developing Sanitation)', domain: 'Agricultural projects', participants: 74 },
    { sno: 5, date: '22.07.22', eventName: 'Workshop on Energy Conservation and Renewable Energy System', domain: 'Livelihood Enhancement', participants: 81 },
    { sno: 6, date: '23.07.22', eventName: 'Workshop on Writing Skills', domain: 'Educational initiatives', participants: 81 },
    { sno: 7, date: '25.07.22', eventName: 'Out Reach Program at Near by School', domain: 'Awareness Compaign', participants: 81 },
    { sno: 8, date: '28.07.22', eventName: 'Sanitation and Hygienic Awareness', domain: 'Health Camps', participants: 70 },
    { sno: 9, date: '14.08.22 & 15.08.22', eventName: 'Electricity connection to all households including from alternative sources of energy', domain: 'Livelihood Enhancement', participants: 110 },
    { sno: 10, date: '25.09.22', eventName: 'Farm Program on Finding and Trouble Shooting Farming Problems', domain: 'Agricultural projects', participants: 88 },
    { sno: 11, date: '16.10.22', eventName: 'Awareness Program on Importance of Food', domain: 'Agricultural projects', participants: 49 },
    { sno: 12, date: '23.10.22', eventName: 'Workshop on Economic Development on promoting Diversified Agriculture Livelihood', domain: 'Agricultural projects', participants: 57 },
    { sno: 13, date: '13.11.22', eventName: 'Workshop on Plant Protection & Importance of Organic Manures in Farming', domain: 'Agricultural projects', participants: 57 },
    { sno: 14, date: '11.12.22', eventName: 'Awareness of Soil Health & Soil Conservation', domain: 'Agricultural projects', participants: 59 },
    { sno: 15, date: '02.01.23', eventName: 'Workshop on Urban Farming & Terrace Gardening', domain: 'Agricultural projects', participants: 70 },
    { sno: 16, date: '30.01.23', eventName: 'Economic Development through Practicing Hygiene Behaviors', domain: 'Agricultural projects', participants: 52 },
    { sno: 17, date: '12.02.23', eventName: 'Awarness of the importance of pulse in the regular diet', domain: 'Health Camps', participants: 54 },
    { sno: 18, date: '03.02.23', eventName: 'Human Development Smart School for Providing Quality Education. Adulliteracy, Village Libraries.', domain: 'Educational initiatives', participants: 85 },
    { sno: 19, date: '14.03.23', eventName: 'Human Development', domain: 'Health Camps', participants: 39 },
    { sno: 20, date: '16.04.23', eventName: 'Awareness on Tree plantation', domain: 'Environmental projects', participants: 59 },
    { sno: 21, date: '17.05.23', eventName: 'Workshop on BEE keeping and Mushroom Cultivation.', domain: 'Agricultural projects', participants: 81 },
  { sno: 22, date: '07.01.22', eventName: 'Blood Grouping', domain: 'Health Camps', participants: 87 },
  { sno: 23, date: '08.01.22', eventName: 'Awareness on Health and Hygiene', domain: 'Health Camps', participants: 94 },
  { sno: 24, date: '18.01.22', eventName: 'Health Camps', domain: 'Health Camps', participants: 86 },
  { sno: 25, date: '24.01.22', eventName: 'Plantation', domain: 'Environmental projects', participants: 92 },
  { sno: 26, date: '09.02.22', eventName: 'Pilot study on Buildings (Govt.), residential buildings, interior and exterior architecture', domain: 'Community Infrastructure', participants: 92 },
  { sno: 27, date: '14.02.22', eventName: 'Pilot study on energy conservation & power consumption', domain: 'Livelihood Enhancement', participants: 84 },
  { sno: 28, date: '18.02.22', eventName: 'Awareness in Technology', domain: 'Educational initiatives', participants: 85 },
  { sno: 29, date: '04.03.22', eventName: 'Pilot study on agriculture, creation of data analysis', domain: 'Agricultural projects', participants: 80 },
  { sno: 30, date: '08.03.22', eventName: 'Projects on conservation Energy', domain: 'Community Infrastructure', participants: 85 },
  { sno: 31, date: '14.03.22', eventName: 'Awareness program on sustainable agriculture', domain: 'Agricultural projects', participants: 84 },
  { sno: 32, date: '18.03.22', eventName: 'Implementing solutions with technology', domain: 'Educational initiatives', participants: 74 },
  { sno: 33, date: '13.04.22', eventName: 'Pilot study on students at village with respect to education, dropouts, highest qualification in studies', domain: 'Educational initiatives', participants: 90 },
  { sno: 34, date: '18.04.22', eventName: 'Awareness program on importance of education', domain: 'Educational initiatives', participants: 80 },
  { sno: 35, date: '21.04.22', eventName: 'Awareness program for girl students on social works', domain: 'Women Empowerment', participants: 85 },
  { sno: 36, date: '23.04.22', eventName: 'Creating learning hub at village', domain: 'Educational initiatives', participants: 89 },
  { sno: 37, date: '02.05.22', eventName: 'Technical interested students to develop technological solutions for problems identified in village', domain: 'Educational initiatives', participants: 71 },
  { sno: 38, date: '03.05.22', eventName: 'Projects to be deployed for the problems identified', domain: 'Community Infrastructure', participants: 71 },
  { sno: 39, date: '11.05.22', eventName: 'Pilot study by students belonging to different departments to identify the problems at village level', domain: 'Community Infrastructure', participants: 71 },
  { sno: 40, date: '22.06.22', eventName: 'Pilot study on Recreations areas', domain: 'Community Infrastructure', participants: 65 },
  { sno: 41, date: '25.06.22', eventName: 'Identification of influencing people at village', domain: 'Community Infrastructure', participants: 69 },
  { sno: 42, date: '28.06.22', eventName: 'Competitions planned at community level', domain: 'Community Infrastructure', participants: 54 },
  { sno: 43, date: '15.07.20', eventName: 'Awareness on safe Disposal of Used Masks in K L E F-SVR Adopted Villages', domain: 'Environmental projects', participants: 80 },
  { sno: 44, date: '27.07.20', eventName: 'Awareness on Swatchata Activities in K L E F-SVR Adopted Villages', domain: 'Environmental projects', participants: 82 },
  { sno: 45, date: '16.08.20', eventName: 'Awareness on De-Worming for the children in K L E F-SVR Adopted Villages', domain: 'Health Camps', participants: 80 },
  { sno: 46, date: '19.08.20', eventName: 'Tree Plantation in K L E F-SVR Adopted Villages', domain: 'Environmental projects', participants: 82 },
  { sno: 47, date: '22.08.20', eventName: 'Awareness on Clay Vinayaka in K L E F-SVR Adopted Villages', domain: 'Environmental projects', participants: 81 },
  { sno: 48, date: '13.08.20 to 15.09.20', eventName: 'Rain water harvesting in K L E F-SVR Adopted Villages', domain: 'Environmental projects', participants: 90 },
  { sno: 49, date: '16.09.20', eventName: 'World Ozone Day in K L E F-SVR Adopted Villages', domain: 'Awareness Compaign', participants: 80 },
  { sno: 50, date: '24.09.20', eventName: 'Awareness on New Education Policy in K L E F-SVR Adopted Villages', domain: 'Awareness Compaign', participants: 80 },
  { sno: 51, date: '30.09.20', eventName: 'Fencing around the Anganwadi School at Porat Nagar', domain: 'Community Infrastructure', participants: 83 },
  { sno: 52, date: '17.09.2019', eventName: 'Household survey at Dasulapalem', domain: 'Community Infrastructure', participants: 90 },
  { sno: 53, date: '10.10.2019', eventName: 'Awareness camp on Anemia at Pulluru', domain: 'Health Camps', participants: 90 },
  { sno: 54, date: '19.12.2019', eventName: 'Rainwater Harvesting at Musunuru', domain: 'Environmental projects', participants: 90 },
  { sno: 55, date: '06.08.2019', eventName: 'Plantation with Geo-tagging at Dasulapalem', domain: 'Environmental projects', participants: 85 },
  { sno: 56, date: '13.08.2019', eventName: 'Plantation with Geo-tagging at Sitarampuram Thanda', domain: 'Environmental projects', participants: 80 },
  { sno: 57, date: '20.08.2019', eventName: 'Plantation with Geo-tagging at Pinapaka', domain: 'Environmental projects', participants: 81 },
  { sno: 58, date: '27.08.2019', eventName: 'Plantation with Geo-tagging at Vellaturu', domain: 'Environmental projects', participants: 85 },
  { sno: 59, date: '03.09.2019', eventName: 'Plantation with Geo-tagging at Porat Nagar', domain: 'Environmental projects', participants: 80 },
  { sno: 60, date: '10.09.2019', eventName: 'Plantation with Geo-tagging at Kanimarla', domain: 'Environmental projects', participants: 80 },
  { sno: 61, date: '17.10.2019', eventName: 'Awareness camp on ODF Kanimarla', domain: 'Health Camps', participants: 80 },
  { sno: 62, date: '27.09.2019', eventName: 'Awareness camp on Plastic-free at Veduru Bedum', domain: 'Environmental projects', participants: 90 },
  { sno: 63, date: '27.09.2019', eventName: 'Awareness camp on Plastic-free at Porat Nagar', domain: 'Environmental projects', participants: 80 },
  { sno: 64, date: '27.09.2019', eventName: 'Awareness camp on Plastic-free at Dasulapalem', domain: 'Environmental projects', participants: 80 },
  { sno: 65, date: '27.09.2019', eventName: 'Awareness camp on Plastic-free at Sitarampuram Thanda', domain: 'Environmental projects', participants: 84 },
  { sno: 66, date: '27.09.2019', eventName: 'Awareness camp on Plastic-free at Vellaturu', domain: 'Environmental projects', participants: 85 },
  { sno: 67, date: '27.09.2019', eventName: 'Awareness camp on Plastic-free at Pinapaka', domain: 'Environmental projects', participants: 86 },
  { sno: 68, date: '27.09.2019', eventName: 'Awareness camp on Plastic-free at Kanimarla', domain: 'Environmental projects', participants: 85 },
  { sno: 69, date: '16.09.2019', eventName: 'Awareness camp on Open Defecation Free at Vedurubedum', domain: 'Health Camps', participants: 85 },
  { sno: 70, date: '16.09.2019', eventName: 'Awareness camp on Open Defecation Free at Porat Nagar', domain: 'Health Camps', participants: 91 },
  { sno: 71, date: '17.09.2019', eventName: 'Awareness camp on Open Defecation Free at Dasulapalem', domain: 'Health Camps', participants: 83 },
  { sno: 72, date: '18.09.2019', eventName: 'Awareness camp on Open Defecation Free at Vellaturu', domain: 'Health Camps', participants: 83 },
  { sno: 73, date: '18.09.2019', eventName: 'Awareness camp on Open Defecation Free at Pinapaka', domain: 'Health Camps', participants: 83 },
  { sno: 74, date: '20.09.2019', eventName: 'Awareness camp on Open Defecation Free at Sitarampuram Thanda', domain: 'Health Camps', participants: 83 },
  { sno: 75, date: '20.09.2019', eventName: 'Awareness camp on Open Defecation Free at Dasulapalem', domain: 'Health Camps', participants: 90 },
  { sno: 76, date: '06.10.2019', eventName: 'Plantation with Geo-tagging at Dasulapalem', domain: 'Environmental projects', participants: 85 },
  { sno: 77, date: '11.10.2019', eventName: 'Plantation with Geo-tagging at Sitarampuram Thanda', domain: 'Environmental projects', participants: 80 },
  { sno: 78, date: '27.11.2019', eventName: 'Plantation with Geo-tagging at Vellaturu', domain: 'Environmental projects', participants: 86 },
  { sno: 79, date: '03.11.2019', eventName: 'Plantation with Geo-tagging at Porat Nagar', domain: 'Environmental projects', participants: 81 },
  { sno: 80, date: '16.12.2019', eventName: 'Plantation with Geo-tagging at Kanimarla', domain: 'Environmental projects', participants: 88 },
  { sno: 81, date: '23.09.2019', eventName: 'Medical Camp at Vellaturu', domain: 'Health Camps', participants: 81 },
  { sno: 82, date: '20.07.2019', eventName: 'Medical Camp at Pinapaka', domain: 'Health Camps', participants: 91 },
  { sno: 83, date: '27.07.2019', eventName: 'Medical Camp at Dasulapalem', domain: 'Health Camps', participants: 80 },
  { sno: 84, date: '17.08.2019', eventName: 'Medical Camp at Porat Nagar', domain: 'Health Camps', participants: 80 },
  { sno: 85, date: '24.08.2019', eventName: 'Medical Camp at Kanimarla', domain: 'Health Camps', participants: 90 },
  { sno: 86, date: '31.08.2019', eventName: 'Medical Camp at Sitarampuram Thanda', domain: 'Health Camps', participants: 80 },
  { sno: 87, date: '14.09.2019', eventName: 'Medical Camp at Vedurubedam', domain: 'Health Camps', participants: 80 },
  { sno: 88, date: '15.09.2019', eventName: 'Medical Camp at Vellaturu', domain: 'Health Camps', participants: 84 },
  { sno: 89, date: '30.09.2019', eventName: 'Medical Camp at Pinapaka', domain: 'Health Camps', participants: 84 },
  { sno: 90, date: '07.10.2019', eventName: 'Medical Camp at Dasulapalem', domain: 'Health Camps', participants: 91 },
  { sno: 91, date: '14.10.2019', eventName: 'Medical Camp at Porat Nagar', domain: 'Health Camps', participants: 90 },
  { sno: 92, date: '21.10.2019', eventName: 'Medical Camp at Kanimarla', domain: 'Health Camps', participants: 80 },
  { sno: 93, date: '10.10.2019', eventName: 'Awareness camp on Anemia at Vellaturu', domain: 'Health Camps', participants: 85 },
  { sno: 94, date: '16.10.2019', eventName: 'Awareness camp on Anemia at Kanimarla', domain: 'Health Camps', participants: 83 },
  { sno: 95, date: '14.10.2019', eventName: 'Awareness camp on Anemia at Porat Nagar', domain: 'Health Camps', participants: 81 },
  { sno: 96, date: '15.10.2019', eventName: 'Awareness camp on Anemia at Dasulapalem', domain: 'Health Camps', participants: 97 },
  { sno: 97, date: '17.10.2019', eventName: 'Awareness camp on Anemia at Pinapaka', domain: 'Health Camps', participants: 90 },
  { sno: 98, date: '22.08.2019', eventName: 'Awareness camp on Anemia at Pulluru', domain: 'Health Camps', participants: 85 },
  { sno: 99, date: '10.10.2019', eventName: 'Awareness camp on Anemia at Sitarampuram tanda', domain: 'Health Camps', participants: 85 },
  { sno: 100, date: '18.10.2019', eventName: 'Awareness camp on Anemia at Vedurubedam', domain: 'Health Camps', participants: 85 },
  { sno: 101, date: '19.10.2019', eventName: 'Awareness camp on Anemia at Mylavaram', domain: 'Health Camps', participants: 84 },
  { sno: 102, date: '22.02.2020', eventName: 'Organisation of vermicompost at Vellaturu', domain: 'Agricultural projects', participants: 80 },
  { sno: 103, date: '11.10.2019', eventName: 'Kitchen Gardening at Vellaturu', domain: 'Agricultural projects', participants: 80 },
  { sno: 104, date: '18.10.2019', eventName: 'Kitchen Gardening at Dasulapalem', domain: 'Agricultural projects', participants: 91 },
  { sno: 105, date: '20.10.2019', eventName: 'Kitchen Gardening at Kanimarla', domain: 'Agricultural projects', participants: 80 },
  { sno: 106, date: '22.10.2019', eventName: 'Kitchen Gardening at Porat Nagar', domain: 'Agricultural projects', participants: 84 },
  { sno: 107, date: '22.10.2019', eventName: 'Kitchen Gardening at Sitarampuram Thanda', domain: 'Agricultural projects', participants: 84 },
  { sno: 108, date: '23.10.2019', eventName: 'Kitchen Gardening at Pinapaka', domain: 'Agricultural projects', participants: 80 },
  { sno: 109, date: '24.10.2019', eventName: 'Kitchen Gardening at Vedurubedam', domain: 'Agricultural projects', participants: 81 },
  { sno: 110, date: '14.09.2019', eventName: 'Awareness on Hand Wash at Vellaturu', domain: 'Health Camps', participants: 84 },
  { sno: 111, date: '15.09.2019', eventName: 'Awareness on Hand Wash at Sitaram Puram Thanda', domain: 'Health Camps', participants: 97 },
  { sno: 112, date: '17.09.2019', eventName: 'Awareness on Hand Wash at Kanimarla', domain: 'Health Camps', participants: 91 },
  { sno: 113, date: '20.09.2019', eventName: 'Awareness on Hand Wash at Pinapaka', domain: 'Health Camps', participants: 94 },
  { sno: 114, date: '14.10.2019', eventName: 'Awareness on Hand Wash at Dasulapalem', domain: 'Health Camps', participants: 80 },
  { sno: 115, date: '18.10.2019', eventName: 'Awareness on Hand Wash at Porat Nagar', domain: 'Health Camps', participants: 80 },
  { sno: 116, date: '10.01.2020', eventName: 'Awareness on Hand Wash at Pulluru', domain: 'Health Camps', participants: 80 },
  { sno: 117, date: '01.12.2019 to 30.12.12', eventName: 'Wall painting at Velvadam', domain: 'Enterprineship development', participants: 84 },
  { sno: 118, date: '16.11.2019 & 17.11.2019', eventName: 'Household survey at Dasulapalem', domain: 'Community Infrastructure', participants: 91 },
  { sno: 119, date: '14.12.2019 to 18.12.2019', eventName: 'Household survey at Sabjapadu', domain: 'Community Infrastructure', participants: 83 },
  { sno: 120, date: '28.12.2019 to 29.12.2019', eventName: 'Household survey at Kanimarla', domain: 'Community Infrastructure', participants: 80 },
  { sno: 121, date: '25.01.2020 to 27.01.2020', eventName: 'Household survey at Pinapaka', domain: 'Community Infrastructure', participants: 84 },
  { sno: 122, date: '28.02.2020', eventName: 'Art and craft work to the School children at Pulluru', domain: 'Educational initiatives', participants: 91 },
  { sno: 123, date: '22.02.2020', eventName: 'Art and craft work to the School children at Dasulapalem', domain: 'Educational initiatives', participants: 80 },
  { sno: 124, date: '30.01.2020', eventName: 'Art and craft work to the School children at Sitaram Puram thanda', domain: 'Educational initiatives', participants: 85 },
  { sno: 125, date: '02.01.2020', eventName: 'Art and craft work to the School children at Kanimarla', domain: 'Educational initiatives', participants: 83 },
  { sno: 126, date: '04.01.2020', eventName: 'Art and craft work to the School children at Porat Nagar', domain: 'Educational initiatives', participants: 90 },
  { sno: 127, date: '05.01.2020', eventName: 'Art and craft work to the School children at Pinapaka', domain: 'Educational initiatives', participants: 97 },
  { sno: 128, date: '06.02.2020', eventName: 'Art and craft work to the School children at Vellaturu', domain: 'Educational initiatives', participants: 90 },
  { sno: 129, date: '07.02.2020', eventName: 'Art and craft work to the School children at Mylavaram', domain: 'Educational initiatives', participants: 83 },
  { sno: 130, date: '11.02.2020', eventName: 'Art and craft work to the School children at G. Konduru', domain: 'Educational initiatives', participants: 91 },
  { sno: 131, date: '13.02.2020', eventName: 'Art and craft work to the School children at Vedurubedam', domain: 'Educational initiatives', participants: 85 },
  { sno: 132, date: '03.09.2019 to 15.11.2019', eventName: 'Awareness on Solid waste management at Vellaturu', domain: 'Environmental projects', participants: 80 },
  { sno: 133, date: '03.09.2019', eventName: 'Awareness on Solid waste management at Veduru bedam', domain: 'Environmental projects', participants: 84 },
  { sno: 134, date: '04.09.2019', eventName: 'Awareness on Solid waste management at Kanimarla', domain: 'Environmental projects', participants: 85 },
  { sno: 135, date: '06.09.2019', eventName: 'Awareness on Solid waste management at Dasulapalem', domain: 'Environmental projects', participants: 90 },
  { sno: 136, date: '07.09.2019', eventName: 'Awareness on Solid waste management at Sitarampuram Thanda', domain: 'Environmental projects', participants: 90 },
  { sno: 137, date: '10.09.2019', eventName: 'Awareness on Solid waste management at Pulluru', domain: 'Environmental projects', participants: 89 },
  { sno: 138, date: '12.09.2019', eventName: 'Awareness on Solid waste management at Pinapaka', domain: 'Environmental projects', participants: 87 },
  { sno: 139, date: '14.09.2019', eventName: 'Awareness on Solid waste management at Mylavaram', domain: 'Environmental projects', participants: 91 },
  { sno: 140, date: '15.09.2019', eventName: 'Awareness on Solid waste management at Porat Nagar', domain: 'Environmental projects', participants: 87 },
  { sno: 141, date: '18.09.2019', eventName: 'Awareness on Solid waste management at Sabjapadu', domain: 'Environmental projects', participants: 90 },
  { sno: 142, date: '21.09.2019', eventName: 'Awareness on Solid waste management at Keerthirayunigudem', domain: 'Environmental projects', participants: 90 },
  { sno: 143, date: '22.09.2019', eventName: 'Awareness on Solid waste management at Chegireddipadu', domain: 'Environmental projects', participants: 85 },
  ];
  
  export default eventData;
  